// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:83d5b5b6-28af-47f2-862a-cd1d74abe88c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ghzm3wDzH",
    "aws_user_pools_web_client_id": "dhick73uuvllc0gc18ukjfobd",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hibqbinfizhxblt6u2o5r7jd7a.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ikgzcg2srnefzphke2xqcl2uky"
};


export default awsmobile;
